// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelAGoogleSubscriptionData, CancelAGoogleSubscriptionResponses, DeferAGoogleSubscriptionData, DeferAGoogleSubscriptionResponses, DeleteOfferingOverrideData, DeleteOfferingOverrideResponses, DeleteSubscriberData, DeleteSubscriberResponses, GetOfferingsData, GetOfferingsErrors, GetOfferingsResponses, GrantAPromotionalEntitlementData, GrantAPromotionalEntitlementResponses, OverrideOfferingData, OverrideOfferingResponses, ReceiptsData, ReceiptsResponses, RefundAGoogleSubscriptionData, RefundAGoogleSubscriptionResponses, RevokeAGoogleSubscriptionData, RevokeAGoogleSubscriptionResponses, RevokePromotionalEntitlementsData, RevokePromotionalEntitlementsResponses, SubscribersattributionData, SubscribersattributionResponses, SubscribersData, SubscribersErrors, SubscribersResponses, UpdateSubscriberAttributesData, UpdateSubscriberAttributesErrors, UpdateSubscriberAttributesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Delete Customer
 *
 * Permanently deletes a customer.
 */
export const deleteSubscriber = <ThrowOnError extends boolean = false>(options: Options<DeleteSubscriberData, ThrowOnError>): RequestResult<DeleteSubscriberResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteSubscriberResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}',
    ...options
});

/**
 * Get or Create Customer
 *
 * Gets the latest [Customer Info](#tag/customer_info_model) for the customer with the given App User ID, or creates a new customer if it doesn't exist.
 */
export const subscribers = <ThrowOnError extends boolean = false>(options: Options<SubscribersData, ThrowOnError>): RequestResult<SubscribersResponses, SubscribersErrors, ThrowOnError> => (options.client ?? client).get<SubscribersResponses, SubscribersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}',
    ...options
});

/**
 * Create a Purchase
 *
 * Records a purchase for a Customer from iOS, Android, or Stripe and will create a Customer if they don't already exist.
 */
export const receipts = <ThrowOnError extends boolean = false>(options: Options<ReceiptsData, ThrowOnError>): RequestResult<ReceiptsResponses, unknown, ThrowOnError> => (options.client ?? client).post<ReceiptsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/receipts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add Customer Attribution Data
 *
 * Attaches attribution data to a subscriber from specific supported networks.
 *
 * @deprecated
 */
export const subscribersattribution = <ThrowOnError extends boolean = false>(options: Options<SubscribersattributionData, ThrowOnError>): RequestResult<SubscribersattributionResponses, unknown, ThrowOnError> => (options.client ?? client).post<SubscribersattributionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/attribution',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Grant an Entitlement
 *
 * Grants a Customer an entitlement. Does not override or defer a store transaction, applied simultaneously.
 */
export const grantAPromotionalEntitlement = <ThrowOnError extends boolean = false>(options: Options<GrantAPromotionalEntitlementData, ThrowOnError>): RequestResult<GrantAPromotionalEntitlementResponses, unknown, ThrowOnError> => (options.client ?? client).post<GrantAPromotionalEntitlementResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/entitlements/{entitlement_identifier}/promotional',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke Granted Entitlements
 *
 * Revokes all granted entitlements for a given entitlement identifier and App User ID.
 */
export const revokePromotionalEntitlements = <ThrowOnError extends boolean = false>(options: Options<RevokePromotionalEntitlementsData, ThrowOnError>): RequestResult<RevokePromotionalEntitlementsResponses, unknown, ThrowOnError> => (options.client ?? client).post<RevokePromotionalEntitlementsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/entitlements/{entitlement_identifier}/revoke_promotionals',
    ...options
});

/**
 * Google Play: Refund and Revoke Subscription
 *
 * Immediately revokes access to a Google Subscription and issues a refund for the last purchase. If you want to refund a one-time Google purchase, see [refund a Google purchase](ref:refund-a-google-subscription).
 */
export const revokeAGoogleSubscription = <ThrowOnError extends boolean = false>(options: Options<RevokeAGoogleSubscriptionData, ThrowOnError>): RequestResult<RevokeAGoogleSubscriptionResponses, unknown, ThrowOnError> => (options.client ?? client).post<RevokeAGoogleSubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/subscriptions/{product_identifier}/revoke',
    ...options
});

/**
 * Update Customer Attributes
 *
 * Updates attributes for a customer.
 */
export const updateSubscriberAttributes = <ThrowOnError extends boolean = false>(options: Options<UpdateSubscriberAttributesData, ThrowOnError>): RequestResult<UpdateSubscriberAttributesResponses, UpdateSubscriberAttributesErrors, ThrowOnError> => (options.client ?? client).post<UpdateSubscriberAttributesResponses, UpdateSubscriberAttributesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/attributes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Google Play: Defer a Subscription
 *
 * Defers the purchase of a Google Subscription to a later date.
 */
export const deferAGoogleSubscription = <ThrowOnError extends boolean = false>(options: Options<DeferAGoogleSubscriptionData, ThrowOnError>): RequestResult<DeferAGoogleSubscriptionResponses, unknown, ThrowOnError> => (options.client ?? client).post<DeferAGoogleSubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/subscriptions/{product_identifier}/defer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Override a Customer's Current Offering
 *
 * Overrides the current Offering for a specific Customer
 */
export const overrideOffering = <ThrowOnError extends boolean = false>(options: Options<OverrideOfferingData, ThrowOnError>): RequestResult<OverrideOfferingResponses, unknown, ThrowOnError> => (options.client ?? client).post<OverrideOfferingResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/offerings/{offering_uuid}/override',
    ...options
});

/**
 * Remove a Customer's Current Offering Override
 *
 * Reset the offering overrides back to the current offering for a specific Customer
 */
export const deleteOfferingOverride = <ThrowOnError extends boolean = false>(options: Options<DeleteOfferingOverrideData, ThrowOnError>): RequestResult<DeleteOfferingOverrideResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteOfferingOverrideResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/offerings/override',
    ...options
});

/**
 * Get Offerings
 *
 * Gets the offerings for your app.
 */
export const getOfferings = <ThrowOnError extends boolean = false>(options: Options<GetOfferingsData, ThrowOnError>): RequestResult<GetOfferingsResponses, GetOfferingsErrors, ThrowOnError> => (options.client ?? client).get<GetOfferingsResponses, GetOfferingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/offerings',
    ...options
});

/**
 * Google Play: Refund and Revoke Purchase
 *
 * Issues a refund for the most recent purchase of a Google product and revokes access. Works for subscription and non-subscription purchases that occurred in the last 365 days.
 */
export const refundAGoogleSubscription = <ThrowOnError extends boolean = false>(options: Options<RefundAGoogleSubscriptionData, ThrowOnError>): RequestResult<RefundAGoogleSubscriptionResponses, unknown, ThrowOnError> => (options.client ?? client).post<RefundAGoogleSubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/transactions/{store_transaction_identifier}/refund',
    ...options
});

/**
 * Google Play: Cancel a Subscription
 *
 * Cancels a Google subscription.
 */
export const cancelAGoogleSubscription = <ThrowOnError extends boolean = false>(options: Options<CancelAGoogleSubscriptionData, ThrowOnError>): RequestResult<CancelAGoogleSubscriptionResponses, unknown, ThrowOnError> => (options.client ?? client).post<CancelAGoogleSubscriptionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/subscribers/{app_user_id}/subscriptions/{store_transaction_identifier}/cancel',
    ...options
});
