// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.revenuecat.com/v1' | (string & {});
};

/**
 * Identifies an error that occurred while processing an API request.
 */
export type Error = {
    /**
     * The error message.
     */
    message?: string;
    /**
     * A numeric error code.
     */
    code?: number;
};

/**
 * Your app's [Offerings and Packages](/getting-started/entitlements).
 */
export type Offerings = {
    /**
     * The identifier of the current Offering for this Customer. [Targeting](/docs/tools/targeting), [Offering overrides](#tag/offerings/operation/override-offering), and [Experiments](/docs/tools/experiments-v1) affect this identifier depending on the App User ID.
     */
    current_offering_id?: string;
    /**
     * A list of available Offerings.
     */
    offerings?: Array<{
        /**
         * The Offering's description.
         */
        description?: string;
        /**
         * The Offering's identifier.
         */
        identifier?: string;
        /**
         * The Packages of this Offering.
         */
        packages?: Array<{
            /**
             * The package's identifier. If you used one of RevenueCat's default identifiers, it will be prefixed by `$rc_`.
             */
            identifier?: string;
            /**
             * The identifier of the product in the store. This should be used to fetch the product from Apple, Google, Amazon, or Stripe depending on the platform. This field will be populated only for the current app based on the API key used and the `X-Platform` header.
             */
            platform_product_identifier?: string;
        }>;
    }>;
};

/**
 * Snapshot of information about a Customer.
 */
export type Subscriber = {
    /**
     * Date of the request in ISO 8601 format.
     */
    request_date?: string;
    /**
     * Date of the request in milliseconds since Epoch.
     */
    request_date_ms?: number;
    /**
     * Information about the Customer.
     */
    subscriber?: {
        /**
         * Dictionary of the entitlements of this Customer (including any expired entitlements).
         */
        entitlements?: {
            [key: string]: {
                /**
                 * Date when the entitlement expires / expired (in ISO 8601 format, may be in the past).
                 */
                expires_date?: string;
                /**
                 * Date when any potential grace period of the entitlement expires / expired (in ISO 8601 format, may be in the past). `null` if the Customer has never been in a grace period.
                 */
                grace_period_expires_date?: string | null;
                /**
                 * The identifier of the product that is responsible for this entitlement being granted.<br><br>Please note: in some cases, if there are problems with validating the purchase with the store, the correct product identifier might temporarily be unavailable.
                 *
                 */
                product_identifier?: string;
                /**
                 * Time of the last purchase or renewal of the product that grants this entitlement (in ISO 8601 format).
                 */
                purchase_date?: string;
            };
        };
        /**
         * The ISO 8601 datetime string corresponding to when the Customer was first seen by RevenueCat.
         */
        first_seen?: string;
        /**
         * The ISO 8601 datetime string corresponding to when the Customer was last seen by RevenueCat.
         */
        last_seen?: string;
        /**
         * URL to manage the active subscription of the Customer. If the Customer has an active iOS subscription, this will point to the App Store, if the Customer has an active Play Store subscription it will point there.
         *
         * If there are no active subscriptions it will be null.
         *
         * If the Customer has multiple active subscriptions for different platforms, this will take the value of the OS in the `X-Platform` header into consideration:
         * - If the request was made on an OS for which there are active subscriptions, this will return the URL for the store that matches the header.
         * - If the request was made on a different OS or the OS was not included in the X-Platform header, this will return the URL for the store of the subscription with the farthest future expiration date.
         *
         */
        management_url?: string;
        /**
         * Non-subscription purchases of the Customer, keyed by the product identifier.
         */
        non_subscriptions?: {
            [key: string]: Array<{
                /**
                 * A unique ID of the purchase.
                 */
                id?: string;
                /**
                 * Whether or not the purchase was made in sandbox mode.
                 */
                is_sandbox?: boolean;
                /**
                 * Date of the purchase (in ISO 8601 format).
                 */
                purchase_date?: string;
                /**
                 * Identifier of the store of the purchase:
                 * - `app_store`: The product was purchased through Apple App Store.
                 * - `mac_app_store`: The product was purchased through the Mac App Store.
                 * - `play_store`: The product was purchased through the Google Play Store.
                 * - `amazon`: The product was purchased through the Amazon Appstore.
                 * - `stripe`: The product was purchased through Stripe.
                 *
                 */
                store?: string;
            }>;
        };
        /**
         * The App User ID under which this Customer was first known to RevenueCat.
         */
        original_app_user_id?: string;
        /**
         * *Only available on iOS*. This will be `null` until an iOS receipt is sent for the Customer. After a receipt has been sent, it will indicate the first App Store version of your app that the Customer installed.
         */
        original_application_version?: string;
        /**
         * **Only available on iOS**. The date that the app was first purchased/downloaded by the Customer. Will be `null` if no receipt is recorded for the Customer. Useful for [Migrating Subscriptions](/docs/migrating-to-revenuecat/migrating-existing-subscriptions).
         */
        original_purchase_date?: string;
        /**
         * @deprecated
         */
        other_purchases?: {
            [key: string]: unknown;
        };
        /**
         * A dictionary of any Attributes set on this Customer. **Only included in responses to requests made with a secret API key**.
         */
        subscriber_attributes?: {
            [key: string]: {
                /**
                 * The value of the attribute.
                 */
                value?: string;
                /**
                 * The time that the Attribut was last updated, in milliseconds since Epoch.
                 */
                updated_at_ms?: number;
            };
        };
        /**
         * Subscription purchases of the Customer, keyed by the product identifier.
         */
        subscriptions?: {
            [key: string]: {
                /**
                 * Date when the subscription will automatically resume after being paused (in ISO 8601 format). Google Play only.
                 */
                auto_resume_date?: string;
                /**
                 * Date when RevenueCat detected any billing issues with this subscription (in ISO 8601 format). If and when the billing issue gets resolved, this field is set to `null`. Note the subscription may still be active, check the `expires_date` attribute.
                 */
                billing_issues_detected_at?: string;
                /**
                 * Date when the subscription expires/expired (in ISO 8601 format).
                 */
                expires_date?: string;
                /**
                 * Date when any grace period for this subscription expires/expired (in ISO 8601 format). `null` if the Customer has never been in a grace period.
                 */
                grace_period_expires_date?: string;
                /**
                 * Whether or not the purchase was made in sandbox mode.
                 */
                is_sandbox?: boolean;
                /**
                 * Date when this subscription first started (in ISO 8601 format). This property does not update with renewals. On iOS, this property also does not update for product changes within a subscription group or resubscriptions by lapsed subscribers.
                 */
                original_purchase_date?: string;
                /**
                 * How the Customer received access to this subscription:
                 * - `PURCHASED`: The Customer purchased the product.
                 * - `FAMILY_SHARED`: The Customer has access to the product via their family.
                 *
                 */
                ownership_type?: 'PURCHASED' | 'FAMILY_SHARED';
                /**
                 * Type of the current subscription period_type:
                 * - `normal`: The product is in a normal period (default)
                 * - `trial`: The product is in a free trial period
                 * - `intro`: The product is in an introductory pricing period
                 *
                 */
                period_type?: 'normal' | 'trial' | 'intro';
                /**
                 * Date when the last subscription period started (in ISO 8601 format).
                 */
                purchase_date?: string;
                /**
                 * Date when RevenueCat detected a refund of this subscription.
                 */
                refunded_at?: string;
                /**
                 * Identifier of the store of the purchase:
                 * - `app_store`: The product was purchased through Apple App Store.
                 * - `mac_app_store`: The product was purchased through the Mac App Store.
                 * - `play_store`: The product was purchased through the Google Play Store.
                 * - `amazon`: The product was purchased through the Amazon Appstore.
                 * - `stripe`: The product was purchased through Stripe.
                 * - `promotional`: The product was [granted via RevenueCat](#tag/entitlements/operation/grant-a-promotional-entitlement).
                 *
                 */
                store?: string;
                /**
                 * Date when RevenueCat detected that auto-renewal was turned off for this subsription (in ISO 8601 format). Note the subscription may still be active, check the `expires_date` attribute.
                 */
                unsubscribe_detected_at?: string;
            };
        };
    };
};

export type DeleteSubscriberData = {
    body?: never;
    path: {
        /**
         * The App User ID of the customer to be deleted (might be an aliased App User ID).
         */
        app_user_id: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}';
};

export type DeleteSubscriberResponses = {
    /**
     * Customer succesfully deleted.
     */
    200: {
        /**
         * The App User ID of the customer that was requested to be deleted
         */
        app_user_id: string;
        /**
         * Whether or not the customer was succesfully deleted
         */
        deleted: boolean;
    };
};

export type DeleteSubscriberResponse = DeleteSubscriberResponses[keyof DeleteSubscriberResponses];

export type SubscribersData = {
    body?: never;
    headers?: {
        /**
         * Optionally set the X-Platform header to update the Customer's `last_seen` field. Set to either `ios`, `android`, `amazon`, `macos`, `uikitformac`. Don't set this if you are calling the getter for informational purposes or using a secret API key to fetch the customer's attributes.
         */
        'X-Platform'?: string;
    };
    path: {
        /**
         * The App User ID used with the mobile SDK.
         */
        app_user_id: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}';
};

export type SubscribersErrors = {
    /**
     * 400
     */
    400: Error;
    /**
     * 401
     */
    401: Error;
};

export type SubscribersError = SubscribersErrors[keyof SubscribersErrors];

export type SubscribersResponses = {
    /**
     * Success (customer found).
     *
     * Returns the [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    200: Subscriber;
    /**
     * Success (customer created).
     *
     * Returns the [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    201: Subscriber;
};

export type SubscribersResponse = SubscribersResponses[keyof SubscribersResponses];

export type ReceiptsData = {
    body?: {
        /**
         * App User ID of the Customer the receipt is associated with.
         */
        app_user_id: string;
        /**
         * For iOS, the base64 encoded receipt file, for Android the receipt token, for Amazon the receipt, and for Stripe the subscription ID or the Stripe Checkout Session ID.
         */
        fetch_token: string;
        /**
         * The Apple, Google, or Amazon product identifier or SKU. Required for Google.
         */
        product_id?: string;
        /**
         * The price of the product. **Required if you provide a currency.**
         */
        price?: number;
        /**
         * The currency of the product. The currency must be in [ISO 4217 format](https://en.wikipedia.org/wiki/ISO_4217). **Required if you provide a price.**
         */
        currency?: string;
        /**
         * Optionally used by the iOS SDK to communicate intro pricing periods. Either `pay_as_you_go = 0`, `pay_up_front = 1`, or `free_trial = 2`. Defaults to `2` (free trial) if an introductory period is detected in the receipt but this value is not provided.
         */
        payment_mode?: string;
        /**
         * Introductory price paid
         */
        introductory_price?: number;
        /**
         * If true, the fetch token will trigger your configured [restore behavior](https://www.revenuecat.com/docs/restoring-purchases#restore-behavior) for any other users sharing the same fetch token.
         *
         * @deprecated
         */
        is_restore?: boolean;
        /**
         * Optional. The offering that was presented to the Customer at the time of purchase.  This will be attached to any new transactions in this fetch token and will be available in ETL exports and webhooks. This is mostly useful if you're sending fetch tokens from your backend.
         */
        presented_offering_identifier?: string;
        /**
         * Any [Attributes](/docs/customers/customer-attributes) to set on the Customer as a dictionary keyed by the Attribute name.
         */
        attributes?: {
            [key: string]: {
                /**
                 * The value of the attribute. If the value is `null` or an empty string, the attribute will be deleted.
                 */
                value: string;
                /**
                 * UNIX epoch in milliseconds of when the attribute was updated. This value is used to resolve conflicts, an attribute will only be updated if the new `updated_at_ms` value is newer than the value for the stored attribute.
                 */
                updated_at_ms?: number;
            };
        };
    };
    headers: {
        /**
         * The platform this purchase is for. Either `ios`, `android`, `amazon`, `macos`, `uikitformac`, or `stripe`
         */
        'X-Platform': string;
    };
    path?: never;
    query?: never;
    url: '/receipts';
};

export type ReceiptsResponses = {
    /**
     * Purchase was successfully posted.
     *
     * Returns the updated [Customer Info](#tag/customer_info_model) for the Customer for which the purchase was posted.
     *
     */
    200: Subscriber;
};

export type ReceiptsResponse = ReceiptsResponses[keyof ReceiptsResponses];

export type SubscribersattributionData = {
    body?: {
        /**
         * The data returned by the attribution network callbacks.
         */
        data: {
            /**
             * The idfa from AdSupport on iOS. (iOS Only)
             */
            rc_idfa?: string;
            /**
             * The Google Play Services Advertising identifier. (Android Only)
             */
            rc_gps_adid?: string;
        };
        /**
         * The attribution network the data is coming from:
         * - 0: Apple Search AdSupport
         * - 1: Adjust
         * - 2: AppsFlyer
         * - 3: Branch
         * - 4: Tenjin
         * - 5: Facebook
         *
         */
        network: '0' | '1' | '2' | '3' | '4' | '5';
    };
    path: {
        /**
         * The App User ID of the Customer.
         */
        app_user_id: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/attribution';
};

export type SubscribersattributionResponses = {
    /**
     * Attribution data was successfully posted.
     */
    200: {
        [key: string]: unknown;
    };
};

export type SubscribersattributionResponse = SubscribersattributionResponses[keyof SubscribersattributionResponses];

export type GrantAPromotionalEntitlementData = {
    body?: {
        /**
         * A Unix epoch in milliseconds for when the entitlement should expire. The entitlement will always be granted immediately. If not provided then `duration` must be provided.
         */
        end_time_ms?: number;
        /**
         * How long of a duration to grant the entitlement for.  If not provided then `end_time_ms` must be provided.
         *
         * @deprecated
         */
        duration?: 'daily' | 'three_day' | 'weekly' | 'two_week' | 'monthly' | 'two_month' | 'three_month' | 'six_month' | 'yearly' | 'lifetime';
        /**
         * A Unix epoch in milliseconds used to determine the expiration date, by adding `duration` to `start_time_ms`. Regardless of what `start_time_ms` is set to, the entitlement will always be granted immediately. If `start_time_ms` is not provided, the `duration` will be added to the current time to determine the expiration date.
         *
         * @deprecated
         */
        start_time_ms?: number;
    };
    path: {
        /**
         * The App User ID of the Customer.
         */
        app_user_id: string;
        /**
         * The identifier for the entitlement you want to grant to the Customer.
         */
        entitlement_identifier: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/entitlements/{entitlement_identifier}/promotional';
};

export type GrantAPromotionalEntitlementResponses = {
    /**
     * Entitlement was successfully granted.
     *
     * Returns the updated [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    201: Subscriber;
};

export type GrantAPromotionalEntitlementResponse = GrantAPromotionalEntitlementResponses[keyof GrantAPromotionalEntitlementResponses];

export type RevokePromotionalEntitlementsData = {
    body?: never;
    path: {
        /**
         * The App User ID of the Customer.
         */
        app_user_id: string;
        /**
         * The identifier for the entitlement you want to revoke from the Customer.
         */
        entitlement_identifier: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/entitlements/{entitlement_identifier}/revoke_promotionals';
};

export type RevokePromotionalEntitlementsResponses = {
    /**
     * Entitlement was succesfully revoked.
     *
     * Returns the updated [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    200: Subscriber;
};

export type RevokePromotionalEntitlementsResponse = RevokePromotionalEntitlementsResponses[keyof RevokePromotionalEntitlementsResponses];

export type RevokeAGoogleSubscriptionData = {
    body?: never;
    path: {
        /**
         * The App User ID of the Customer.
         */
        app_user_id: string;
        /**
         * The identifier of the product belonging to the subscription that is being revoked.
         */
        product_identifier: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/subscriptions/{product_identifier}/revoke';
};

export type RevokeAGoogleSubscriptionResponses = {
    /**
     * Subscription was successfully refunded and revoked.
     *
     * Returns the updated [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    200: Subscriber;
};

export type RevokeAGoogleSubscriptionResponse = RevokeAGoogleSubscriptionResponses[keyof RevokeAGoogleSubscriptionResponses];

export type UpdateSubscriberAttributesData = {
    body?: {
        attributes?: {
            /**
             * Mapping of keys to attribute values.
             */
            key_name: {
                /**
                 * The value of the attribute. If the value is `null` or an empty string, the attribute will be deleted.
                 */
                value: string;
                /**
                 * UNIX epoch in milliseconds of when the attribute was updated. This value is used to resolve conflicts, an attribute will only be updated if the new `updated_at_ms` value is newer than the value for the stored attribute.
                 */
                updated_at_ms?: number;
            };
        };
    };
    path: {
        /**
         * The App User ID used with the mobile SDK.
         */
        app_user_id: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/attributes';
};

export type UpdateSubscriberAttributesErrors = {
    /**
     * 400
     */
    400: {
        code?: number;
        message?: string;
        attribute_errors?: Array<{
            key_name?: string;
            message?: string;
        }>;
    };
};

export type UpdateSubscriberAttributesError = UpdateSubscriberAttributesErrors[keyof UpdateSubscriberAttributesErrors];

export type UpdateSubscriberAttributesResponses = {
    /**
     * Attributes were successfully updated.
     *
     * Returns the updated [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    200: Subscriber;
};

export type UpdateSubscriberAttributesResponse = UpdateSubscriberAttributesResponses[keyof UpdateSubscriberAttributesResponses];

export type DeferAGoogleSubscriptionData = {
    body?: {
        /**
         * The desired next expiry time to assign to the subscription, in milliseconds since the Epoch. The given time must be later/greater than the current expiry time for the subscription.
         */
        expiry_time_ms: number;
    };
    path: {
        /**
         * The App User ID of the Customer.
         */
        app_user_id: string;
        /**
         * The identifier of the product belonging to the subscription that is being deferred.
         */
        product_identifier: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/subscriptions/{product_identifier}/defer';
};

export type DeferAGoogleSubscriptionResponses = {
    /**
     * Subscription was successfully deferred.
     *
     * Returns the updated [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    200: Subscriber;
};

export type DeferAGoogleSubscriptionResponse = DeferAGoogleSubscriptionResponses[keyof DeferAGoogleSubscriptionResponses];

export type OverrideOfferingData = {
    body?: never;
    path: {
        /**
         * The App User ID of the Customer.
         */
        app_user_id: string;
        /**
         * The UUID for the offering you want to set as the override for the Customer. The UUID can be found in the URL of the offering. For example, the offering UUID in https://app.revenuecat.com/apps/abcd1234/offerings/ofrng1234567abc is `ofrng1234567abc`.
         */
        offering_uuid: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/offerings/{offering_uuid}/override';
};

export type OverrideOfferingResponses = {
    /**
     * Offering was succesfully overridden.
     *
     * Returns the updated [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    201: Subscriber;
};

export type OverrideOfferingResponse = OverrideOfferingResponses[keyof OverrideOfferingResponses];

export type DeleteOfferingOverrideData = {
    body?: never;
    path: {
        /**
         * The App User ID of the Customer.
         */
        app_user_id: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/offerings/override';
};

export type DeleteOfferingOverrideResponses = {
    /**
     * Offering override was succesfully removed.
     *
     * Returns the updated [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    201: Subscriber;
};

export type DeleteOfferingOverrideResponse = DeleteOfferingOverrideResponses[keyof DeleteOfferingOverrideResponses];

export type GetOfferingsData = {
    body?: never;
    headers?: {
        /**
         * Set the X-Platform header to fetch that platform's packages. Can be `ios`, `android`, `amazon`, or `stripe`.
         * This header is required if you use a legacy public API key to determine which store the products should be returned for. It is not required if you use a new, app-specific API key, in which case the products for the app associated with the API key will be returned.
         */
        'X-Platform'?: string;
    };
    path: {
        /**
         * The App User ID used with the mobile SDK. The App User ID doesn't have to exist for the endpoint to work but it can affect the current offering depending on whether you have any [Experiments](https://www.revenuecat.com/docs/tools/experiments-v1) running or have [overridden the current offering](ref:override-offering) for this specific App User ID.
         */
        app_user_id: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/offerings';
};

export type GetOfferingsErrors = {
    /**
     * 400
     */
    400: Error;
    /**
     * 403
     */
    403: {
        code?: number;
        message?: string;
    };
};

export type GetOfferingsError = GetOfferingsErrors[keyof GetOfferingsErrors];

export type GetOfferingsResponses = {
    /**
     * [Offerings](#tag:offerings_model) for the Customer.
     */
    200: Offerings;
};

export type GetOfferingsResponse = GetOfferingsResponses[keyof GetOfferingsResponses];

export type RefundAGoogleSubscriptionData = {
    body?: never;
    path: {
        /**
         * The App User ID of the Customer.
         */
        app_user_id: string;
        /**
         * The identifier of the transaction to refund. Example: GPA.3309-9122-6177-45730
         */
        store_transaction_identifier: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/transactions/{store_transaction_identifier}/refund';
};

export type RefundAGoogleSubscriptionResponses = {
    /**
     * Purchase was succesfully refunded and revoked.
     *
     * Returns the updated [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    200: Subscriber;
};

export type RefundAGoogleSubscriptionResponse = RefundAGoogleSubscriptionResponses[keyof RefundAGoogleSubscriptionResponses];

export type CancelAGoogleSubscriptionData = {
    body?: never;
    path: {
        /**
         * The App User ID of the Customer.
         */
        app_user_id: string;
        /**
         * The identifier of the transaction to cancel. Example: GPA.3309-9122-6177-45730
         */
        store_transaction_identifier: string;
    };
    query?: never;
    url: '/subscribers/{app_user_id}/subscriptions/{store_transaction_identifier}/cancel';
};

export type CancelAGoogleSubscriptionResponses = {
    /**
     * Subscription was succesfully canceled.
     *
     * Returns the updated [Customer Info](#tag/customer_info_model) for the Customer.
     *
     */
    200: Subscriber;
};

export type CancelAGoogleSubscriptionResponse = CancelAGoogleSubscriptionResponses[keyof CancelAGoogleSubscriptionResponses];
