name: Publish

on: push

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v6
        with:
          node-version: latest
          registry-url: "https://registry.npmjs.org"
      - run: bun install
      - run: bun run generate
      - run: bun run build
      - run: npm publish --provenance --access public
        continue-on-error: true